//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SECURITY.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class audience
    {
        public string AudienceId { get; set; }
        public string InternalId { get; set; }
        public string Name { get; set; }
        public string Secret { get; set; }
        public int DaysToExpire { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public bool IsInternal { get; set; }
        public bool IsActive { get; set; }
    }
}
