//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ePassport.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vuelo
    {
        public int VueloId { get; set; }
        public long UserId { get; set; }
        public string Localizador { get; set; }
        public string Origen { get; set; }
        public string Destino { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public Nullable<System.DateTime> HoraLlegada { get; set; }
        public string OACI { get; set; }
    
        public virtual usuario usuario { get; set; }
    }
}
